# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='cap',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='token',
            name='ether_price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='token',
            name='symbol',
            field=models.CharField(default='TKN', max_length=100),
            preserve_default=False,
        ),
    ]
